from .web_project_generator import WebProjectGenerator
from .web_model_generator import WebModelGenerator
from .web_resource_generator import WebResourceGenerator
from .web_authentication_generator import WebAuthenticationGenerator